
- include: galaxy_root.yml
  when: galaxy_extras_config_galaxy_root

- include: galaxy_metrics.yml
  when: galaxy_extras_config_galaxy_root

- include: uwsgi.yml
  when: galaxy_extras_config_uwsgi

- include: nginx.yml
  when: galaxy_extras_config_nginx

- include: proftpd.yml
  when: galaxy_extras_config_proftpd

- include: slurm.yml
  when: galaxy_extras_config_slurm

- include: supervisor.yml
  when: galaxy_extras_config_supervisor
